openapi: 3.0.0
info:
  title: CampusMart API
  description: API documentation for the CampusMart marketplace.
  version: 1.0.0

servers:
  - url: http://localhost:5000/api/v1

paths:
  /register:
    post:
      summary: User Registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad Request

  /login:
    post:
      summary: User Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Unauthorized

  /logout:
    post:
      summary: User Logout
      responses:
        '200':
          description: Logout successful
        '401':
          description: Unauthorized

  /profile:
    get:
      summary: Get User Profile
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  email:
                    type: string

    put:
      summary: Edit User Profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User profile updated successfully
        '400':
          description: Bad Request

  /listings:
    get:
      summary: Get All Listings
      responses:
        '200':
          description: A list of all listings
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    price:
                      type: number

    post:
      summary: Create New Listing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: number
      responses:
        '201':
          description: Listing created successfully
        '400':
          description: Bad Request

  /listings/{listing_id}:
    get:
      summary: Get Listing Details
      parameters:
        - name: listing_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Listing details retrieved successfully
        '404':
          description: Listing not found

    put:
      summary: Edit Listing
      parameters:
        - name: listing_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: number
      responses:
        '200':
          description: Listing updated successfully
        '404':
          description: Listing not found

    delete:
      summary: Delete Listing
      parameters:
        - name: listing_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Listing deleted successfully
        '404':
          description: Listing not found

  /transactions/buy:
    post:
      summary: Buy Item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                listing_id:
                  type: integer
                quantity:
                  type: integer
      responses:
        '200':
          description: Purchase successful
        '400':
          description: Bad Request

  /transactions/history:
    get:
      summary: Transaction History
      responses:
        '200':
          description: A list of user's transaction history
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    transaction_id:
                      type: integer
                    date:
                      type: string
                      format: date
                    amount:
                      type: number

  /chat-partners:
    get:
      summary: Get Chat Partners
      responses:
        '200':
          description: List of chat partners retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    user_id:
                      type: integer
                    username:
                      type: string

  /messages/{user_id}:
    parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Get Messages
      responses:
        '200':
          description: Messages retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    message_id:
                      type: integer
                    content:
                      type: string
                    timestamp:
                      type: string
                      format: date-time

    post:
      summary: Send Message
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        '200':
          description: Message sent successfully
        '400':
          description: Bad Request

  /contact:
    post:
      summary: Contact Us
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                message:
                  type: string
      responses:
        '200':
          description: Message sent successfully
        '400':
          description: Bad Request

  /terms:
    get:
      summary: Terms and Conditions
      responses:
        '200':
          description: Terms and conditions retrieved successfully
          content:
            text/plain:
              schema:
                type: string
