# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ContactBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, email: str=None, message: str=None):  # noqa: E501
        """ContactBody - a model defined in Swagger

        :param name: The name of this ContactBody.  # noqa: E501
        :type name: str
        :param email: The email of this ContactBody.  # noqa: E501
        :type email: str
        :param message: The message of this ContactBody.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'name': str,
            'email': str,
            'message': str
        }

        self.attribute_map = {
            'name': 'name',
            'email': 'email',
            'message': 'message'
        }
        self._name = name
        self._email = email
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ContactBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The contact_body of this ContactBody.  # noqa: E501
        :rtype: ContactBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ContactBody.


        :return: The name of this ContactBody.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ContactBody.


        :param name: The name of this ContactBody.
        :type name: str
        """

        self._name = name

    @property
    def email(self) -> str:
        """Gets the email of this ContactBody.


        :return: The email of this ContactBody.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this ContactBody.


        :param email: The email of this ContactBody.
        :type email: str
        """

        self._email = email

    @property
    def message(self) -> str:
        """Gets the message of this ContactBody.


        :return: The message of this ContactBody.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ContactBody.


        :param message: The message of this ContactBody.
        :type message: str
        """

        self._message = message
