# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, transaction_id: int=None, _date: date=None, amount: float=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param transaction_id: The transaction_id of this InlineResponse2002.  # noqa: E501
        :type transaction_id: int
        :param _date: The _date of this InlineResponse2002.  # noqa: E501
        :type _date: date
        :param amount: The amount of this InlineResponse2002.  # noqa: E501
        :type amount: float
        """
        self.swagger_types = {
            'transaction_id': int,
            '_date': date,
            'amount': float
        }

        self.attribute_map = {
            'transaction_id': 'transaction_id',
            '_date': 'date',
            'amount': 'amount'
        }
        self._transaction_id = transaction_id
        self.__date = _date
        self._amount = amount

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def transaction_id(self) -> int:
        """Gets the transaction_id of this InlineResponse2002.


        :return: The transaction_id of this InlineResponse2002.
        :rtype: int
        """
        return self._transaction_id

    @transaction_id.setter
    def transaction_id(self, transaction_id: int):
        """Sets the transaction_id of this InlineResponse2002.


        :param transaction_id: The transaction_id of this InlineResponse2002.
        :type transaction_id: int
        """

        self._transaction_id = transaction_id

    @property
    def _date(self) -> date:
        """Gets the _date of this InlineResponse2002.


        :return: The _date of this InlineResponse2002.
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date: date):
        """Sets the _date of this InlineResponse2002.


        :param _date: The _date of this InlineResponse2002.
        :type _date: date
        """

        self.__date = _date

    @property
    def amount(self) -> float:
        """Gets the amount of this InlineResponse2002.


        :return: The amount of this InlineResponse2002.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount: float):
        """Sets the amount of this InlineResponse2002.


        :param amount: The amount of this InlineResponse2002.
        :type amount: float
        """

        self._amount = amount
