# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, title: str=None, price: float=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param id: The id of this InlineResponse2001.  # noqa: E501
        :type id: int
        :param title: The title of this InlineResponse2001.  # noqa: E501
        :type title: str
        :param price: The price of this InlineResponse2001.  # noqa: E501
        :type price: float
        """
        self.swagger_types = {
            'id': int,
            'title': str,
            'price': float
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'price': 'price'
        }
        self._id = id
        self._title = title
        self._price = price

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this InlineResponse2001.


        :return: The id of this InlineResponse2001.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this InlineResponse2001.


        :param id: The id of this InlineResponse2001.
        :type id: int
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this InlineResponse2001.


        :return: The title of this InlineResponse2001.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this InlineResponse2001.


        :param title: The title of this InlineResponse2001.
        :type title: str
        """

        self._title = title

    @property
    def price(self) -> float:
        """Gets the price of this InlineResponse2001.


        :return: The price of this InlineResponse2001.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this InlineResponse2001.


        :param price: The price of this InlineResponse2001.
        :type price: float
        """

        self._price = price
