# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2003(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_id: int=None, username: str=None):  # noqa: E501
        """InlineResponse2003 - a model defined in Swagger

        :param user_id: The user_id of this InlineResponse2003.  # noqa: E501
        :type user_id: int
        :param username: The username of this InlineResponse2003.  # noqa: E501
        :type username: str
        """
        self.swagger_types = {
            'user_id': int,
            'username': str
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'username': 'username'
        }
        self._user_id = user_id
        self._username = username

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2003':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3 of this InlineResponse2003.  # noqa: E501
        :rtype: InlineResponse2003
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> int:
        """Gets the user_id of this InlineResponse2003.


        :return: The user_id of this InlineResponse2003.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this InlineResponse2003.


        :param user_id: The user_id of this InlineResponse2003.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def username(self) -> str:
        """Gets the username of this InlineResponse2003.


        :return: The username of this InlineResponse2003.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this InlineResponse2003.


        :param username: The username of this InlineResponse2003.
        :type username: str
        """

        self._username = username
