# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MessagesUserIdBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, content: str=None):  # noqa: E501
        """MessagesUserIdBody - a model defined in Swagger

        :param content: The content of this MessagesUserIdBody.  # noqa: E501
        :type content: str
        """
        self.swagger_types = {
            'content': str
        }

        self.attribute_map = {
            'content': 'content'
        }
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'MessagesUserIdBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The messages_user_id_body of this MessagesUserIdBody.  # noqa: E501
        :rtype: MessagesUserIdBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def content(self) -> str:
        """Gets the content of this MessagesUserIdBody.


        :return: The content of this MessagesUserIdBody.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this MessagesUserIdBody.


        :param content: The content of this MessagesUserIdBody.
        :type content: str
        """

        self._content = content
