# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TransactionsBuyBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, listing_id: int=None, quantity: int=None):  # noqa: E501
        """TransactionsBuyBody - a model defined in Swagger

        :param listing_id: The listing_id of this TransactionsBuyBody.  # noqa: E501
        :type listing_id: int
        :param quantity: The quantity of this TransactionsBuyBody.  # noqa: E501
        :type quantity: int
        """
        self.swagger_types = {
            'listing_id': int,
            'quantity': int
        }

        self.attribute_map = {
            'listing_id': 'listing_id',
            'quantity': 'quantity'
        }
        self._listing_id = listing_id
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'TransactionsBuyBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The transactions_buy_body of this TransactionsBuyBody.  # noqa: E501
        :rtype: TransactionsBuyBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def listing_id(self) -> int:
        """Gets the listing_id of this TransactionsBuyBody.


        :return: The listing_id of this TransactionsBuyBody.
        :rtype: int
        """
        return self._listing_id

    @listing_id.setter
    def listing_id(self, listing_id: int):
        """Sets the listing_id of this TransactionsBuyBody.


        :param listing_id: The listing_id of this TransactionsBuyBody.
        :type listing_id: int
        """

        self._listing_id = listing_id

    @property
    def quantity(self) -> int:
        """Gets the quantity of this TransactionsBuyBody.


        :return: The quantity of this TransactionsBuyBody.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this TransactionsBuyBody.


        :param quantity: The quantity of this TransactionsBuyBody.
        :type quantity: int
        """

        self._quantity = quantity
